[package]
name = "ignite-rs"
version = "0.1.1"
authors = ["Andrii Pohrebniak <andrii.pohrebniak@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Apache Ignite thin client"
homepage = "https://github.com/apohrebniak/ignite-rs"
documentation = "https://github.com/apohrebniak/ignite-rs"
repository = "https://github.com/apohrebniak/ignite-rs"
readme = "README.md"
keywords = ["ignite","client"]
categories = ["database"]

[dependencies]
arc-swap = "1"
bytes = "1"

[dependencies.tokio]
version = "1"
features = ["net", "io-util", "sync", "time", "rt", "macros"]

[dependencies.tokio-rustls]
version = "0.25"
optional = true

[dev-dependencies]
hex-literal = "0.4.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "io-util", "net", "process"] }
criterion = { version = "0.5", features = ["async_tokio"] }
dhat = "0.3"
ignite-rs_derive = { path = "../ignite-rs_derive" }
testcontainers = { version = "0.15", features = ["experimental"] }
bollard = "0.13"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.rustls]
version = "0.22"
optional = true

[dependencies.rustls-pemfile]
version = "1"
optional = true

[features]
default = []
ssl = ["rustls", "tokio-rustls", "rustls-pemfile"]
rt-tokio = []

[[bench]]
name = "sync_async_bench"
harness = false

[[bench]]
name = "hot_path"
harness = false

[[example]]
name = "dhat_hot_path"
